# Generated by Django 3.2.9 on 2021-12-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
