# Generated by Django 3.2.9 on 2021-12-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_alter_student_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
