# Generated by Django 3.2.9 on 2021-12-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(null=True, through='students_app.CourseEnrollment', to='students_app.Student'),
        ),
    ]
