# Generated by Django 3.2.9 on 2021-12-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0008_alter_subject_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='grades',
        ),
    ]
