# Generated by Django 3.2.9 on 2021-12-11 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0010_courseenrollment_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='date_enrolled',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
