# Generated by Django 3.2.9 on 2021-12-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0014_auto_20211211_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='grades_list',
        ),
    ]
