# Generated by Django 3.2.9 on 2021-12-11 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0015_remove_courseenrollment_grades_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='grades_list',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
